### ISSUE TITLE
Error when two images are identical

### ISSUE THREAD

**Issue by RezaRahmati** [richclement/ImageDiff#1]
If tow images are identical you will get an exception for fixing that I changed Compare method to this

```
    public Bitmap Compare(Bitmap firstImage, Bitmap secondImage)
    {
        if (firstImage == null) throw new ArgumentNullException("firstImage");
        if (secondImage == null) throw new ArgumentNullException("secondImage");
        if (firstImage.Width != secondImage.Width || firstImage.Height != secondImage.Height) throw new ArgumentException("Bitmaps must be the same size.");

        var differenceMap = BitmapAnalyzer.Analyze(firstImage, secondImage);

        if (differenceMap.Cast<bool>().Any(i => i))
        {

            var differenceLabels = Labeler.Label(differenceMap);
            var boundingBoxes = BoundingBoxIdentifier.CreateBoundingBoxes(differenceLabels);
            var differenceBitmap = CreateImageWithBoundingBoxes(secondImage, boundingBoxes);
            return differenceBitmap;
        }
        return null;
    }
```

and even I used the side effect, when they are identical I get the null as result.

**Comment by richclement** [comment]
Thanks for the logged issue. I see the root cause is in `IBoundingBoxIdentifier` implementation. I will update the code to fix this and not change the return options for `Compare`.

**Comment by RezaRahmati** [comment]
@richclement Thanks for fast response, so by this change, how we can find out that the files were identical?
 in our project we want to save the difference and throw exception if they are not identical and do nothing if they are identical.

**Comment by richclement** [comment]
I can add an additional method to the `IImageComparer` interface. Something like `bool Equals(T firstImage, T secondImage)`. This would use the `IBitmapAnalyzer` strategy that the Comparer is initialized with and effectively short circuit the processes after analyzing the images. This would avoid labeling and building bounding boxes for the image.
